import { Client } from './types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: '1',
    name: 'Transvale Logística',
    contato: 'Roberto Alencar',
    whatsapp: '11988223344',
    email: 'roberto@transvale.com',
    type: 'Frotista',
    size: 'Grande',
    pipelineStage: 0,
    ticketMedio: 15000,
    frequencia: 2,
    score: 45,
    tier: 'B',
    ultimaInteracao: 'Enviou proposta via Zap',
    nurtureActive: true,
    nurtureStep: 1,
    notas: 'Frota pesada, interesse em lubrificantes',
    endereco: 'Rua das Industrias, 1200 - São Paulo, SP',
    potencialMapeado: true,
    gapVenda: 12000,
    margem: 15,
    sensibilidadePreco: 'Média',
    dependenciaOp: 4,
    crossSell: 'Filtros, Graxas',
    upsell: 'Contrato Fidelidade'
  },
  {
    id: '2',
    name: 'Fazenda Rio Grande',
    contato: 'Sérgio Santos',
    whatsapp: '41999887766',
    email: 'sergio@riogrande.com',
    type: 'Agro',
    size: 'Médio',
    pipelineStage: 2,
    ticketMedio: 8000,
    frequencia: 1,
    score: 25,
    tier: 'C',
    ultimaInteracao: 'Aguardando vistoria',
    nurtureActive: true,
    nurtureStep: 0,
    notas: 'Grande potencial de expansão para safra de 2024',
    endereco: 'Av. Brasil, s/n - Fazenda Nova, PR',
    potencialMapeado: true,
    gapVenda: 45000,
    margem: 12,
    sensibilidadePreco: 'Média',
    dependenciaOp: 5,
    crossSell: 'Lubrificante p/ Trator',
    upsell: 'Aditivos Premium'
  },
  {
    id: '3',
    name: 'Indústria Metalúrgica ABC',
    contato: 'Cláudia Silva',
    whatsapp: '11977665544',
    email: 'claudia@industriaabc.com',
    type: 'Indústria',
    size: 'Grande',
    pipelineStage: 1,
    ticketMedio: 45000,
    frequencia: 4,
    score: 82,
    tier: 'A',
    ultimaInteracao: 'Reunião marcada p/ terça',
    nurtureActive: false,
    nurtureStep: 0,
    notas: 'Exige relatórios de sustentabilidade mensalmente',
    endereco: 'Rua Metalúrgica, 450 - São Caetano do Sul, SP',
    potencialMapeado: true,
    gapVenda: 8000,
    margem: 18,
    sensibilidadePreco: 'Baixa',
    dependenciaOp: 2,
    crossSell: 'Limpeza de Bico',
    upsell: 'Consultoria de Eficiência'
  },
  {
    id: '4',
    name: 'Revenda Auto Peças Sul',
    contato: 'Marcos Vinícius',
    whatsapp: '51988221122',
    email: 'marcos@revenda-sul.com',
    type: 'Revenda',
    size: 'Médio',
    pipelineStage: 3,
    ticketMedio: 22000,
    frequencia: 8,
    score: 95,
    tier: 'S',
    ultimaInteracao: 'Contrato assinado',
    nurtureActive: false,
    nurtureStep: 0,
    notas: 'Interesse em atalhos para compras rápidas via portal',
    endereco: 'Av. Sertório, 890 - Porto Alegre, RS',
    potencialMapeado: false,
    gapVenda: 0,
    margem: 20,
    sensibilidadePreco: 'Alta',
    dependenciaOp: 3,
    crossSell: 'Filtro Ar',
    upsell: 'Seguro de Carga'
  },
  {
    id: '5',
    name: 'José Caminhoneiro Autônomo',
    contato: 'José Ferreira',
    whatsapp: '21988776655',
    email: 'jose.caminhao@outlook.com',
    type: 'Autônomo',
    size: 'Pequeno',
    pipelineStage: 0,
    ticketMedio: 2500,
    frequencia: 1,
    score: 12,
    tier: 'D',
    ultimaInteracao: 'Primeiro contato realizado',
    nurtureActive: true,
    nurtureStep: 2,
    notas: 'Negociação frequente por preço e volume',
    endereco: 'Posto Graal, BR-116 - Km 45, RJ',
    potencialMapeado: true,
    gapVenda: 25000,
    margem: 10,
    sensibilidadePreco: 'Alta',
    dependenciaOp: 4,
    crossSell: 'Graxas e Estopa',
    upsell: 'Combustível Aditivado'
  }
];
