import { Client } from './types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: '1',
    name: 'Transvale Logística',
    contato: 'Roberto Alencar',
    whatsapp: '11988223344',
    email: 'roberto@transvale.com',
    type: 'Frotista',
    size: 'Grande',
    pipelineStage: 0,
    ticketMedio: 15000,
    frequencia: 2,
    score: 45,
    tier: 'B',
    ultimaInteracao: 'Enviou proposta via Zap',
    nurtureActive: true,
    nurtureStep: 1,
    notas: 'Frota pesada, interesse em lubrificantes'
  },
  {
    id: '2',
    name: 'Fazenda Rio Grande',
    contato: 'Sérgio Santos',
    whatsapp: '41999887766',
    email: 'sergio@riogrande.com',
    type: 'Agro',
    size: 'Médio',
    pipelineStage: 2,
    ticketMedio: 8000,
    frequencia: 1,
    score: 25,
    tier: 'C',
    ultimaInteracao: 'Aguardando vistoria',
    nurtureActive: true,
    nurtureStep: 0,
    notas: 'Manutenção pré-safra'
  },
  {
    id: '3',
    name: 'Indústria Metalúrgica ABC',
    contato: 'Cláudia Silva',
    whatsapp: '11977665544',
    email: 'claudia@industriaabc.com',
    type: 'Indústria',
    size: 'Grande',
    pipelineStage: 1,
    ticketMedio: 45000,
    frequencia: 4,
    score: 82,
    tier: 'A',
    ultimaInteracao: 'Reunião marcada p/ terça',
    nurtureActive: false,
    nurtureStep: 0,
    notas: 'Potencial global de lubrificantes'
  },
  {
    id: '4',
    name: 'Revenda Auto Peças Sul',
    contato: 'Marcos Vinícius',
    whatsapp: '51988221122',
    email: 'marcos@revenda-sul.com',
    type: 'Revenda',
    size: 'Médio',
    pipelineStage: 3,
    ticketMedio: 22000,
    frequencia: 8,
    score: 95,
    tier: 'S',
    ultimaInteracao: 'Contrato assinado',
    nurtureActive: false,
    nurtureStep: 0,
    notas: 'Distribuição regional'
  },
  {
    id: '5',
    name: 'José Caminhoneiro Autônomo',
    contato: 'José Ferreira',
    whatsapp: '21988776655',
    email: 'jose.caminhao@outlook.com',
    type: 'Autônomo',
    size: 'Pequeno',
    pipelineStage: 0,
    ticketMedio: 2500,
    frequencia: 1,
    score: 12,
    tier: 'D',
    ultimaInteracao: 'Primeiro contato realizado',
    nurtureActive: true,
    nurtureStep: 2,
    notas: 'Dificuldade de caixa, focar em economia'
  }
];
